server:
  port: 9195
  servlet.context-path: /kafka
  undertow.max-http-post-size: 0
spring:
  application.name: kafka
  main.allow-bean-definition-overriding: true
  profiles.active: dev
  jackson.default-property-inclusion: non_absent

spring.kafka.bootstrap-servers: localhost:9092
topic.string: STRING_TOPIC
topic.long.message: longMessage
topic.greeting: GREETING_TOPIC
topic.multiType: MULTI_TYPE_TOPIC

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.FilterChainProxy: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE