server:
  port: 9195
  servlet.context-path: /kafka
  undertow.max-http-post-size: 0
spring:
  application.name: kafka
  main.allow-bean-definition-overriding: true
  profiles.active: dev
  jackson.default-property-inclusion: non_absent

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: demo-group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.FilterChainProxy: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

topic.jack: FIRST_TOPIC
topic.long.message: longMessage
topic.greeting: GREETING_TOPIC
#filtered.topic.name: filtered
#partitioned.topic.name: partitioned
#multi.type.topic.name: multitype