server:
  port: 9193
  servlet.context-path: /jpa
  undertow.max-http-post-size: 0
spring:
  application.name: jpa
  main.allow-bean-definition-overriding: true
  profiles:
    active: dev
  jackson.default-property-inclusion: non_absent
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        generate_statistics: true
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
#        use-new-id-generator-mappings: false
#    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/sakila
#    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: 123456

#logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    org.springframework.web.FilterChainProxy: DEBUG
#    org.springframework.web.client.RestTemplate: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.boot.autoconfigure: INFO
