server:
  port: 9193
  servlet.context-path: /jpa
  undertow.max-http-post-size: 0
spring:
  application.name: jpa
  main.allow-bean-definition-overriding: true
  profiles:
    active: dev
  jackson.default-property-inclusion: non_absent
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/sakila
    username: root
    password: 123456

#logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    org.springframework.web.FilterChainProxy: DEBUG
#    org.springframework.web.client.RestTemplate: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.boot.autoconfigure: INFO
